// Generated by ts-to-zod
import { z } from 'zod'

export const panelMatchSchema = z.union([
  z.object({
    name: z.literal('string'),
  }),
  z.object({
    name: z.literal('boolean'),
  }),
  z.object({
    name: z.literal('enum'),
    parameters: z.object({
      values: z.array(z.string()),
    }),
  }),
  z.object({
    name: z.literal('SxProps'),
  }),
])

export const existingAttributeValueObjectSchema = z.array(
  z.object({
    value: z.string(),
    name: z.string(),
  })
)

export const existingAttributeValueSchema = z.union([z.string(), existingAttributeValueObjectSchema])

const locationSchema = z.object({
  pos: z.number(),
  end: z.number(),
})

export const existingAttributeSchema = z.object({
  name: z.string(),
  value: existingAttributeValueSchema.optional(),
  location: locationSchema,
})

export const panelAttributeSchema = z.object({
  name: z.string(),
  location: locationSchema.optional(),
  required: z.boolean().optional(),
  panels: z.array(panelMatchSchema),
})

export const iRangeSchema = z.object({
  startLineNumber: z.number(),
  startColumn: z.number(),
  endLineNumber: z.number(),
  endColumn: z.number(),
})

export const panelsResponseSchema = z.object({
  attributes: z.array(panelAttributeSchema),
  existingAttributes: z.array(existingAttributeSchema),
  location: z.number().optional(),
  fileName: z.string().optional(),
  range: iRangeSchema.optional(),
})
